from app.schemas.analytics import DistrictOverviewResponse, OfficerMetric, TehsilSummary
from app.schemas.application import (
    ApplicationCreate,
    ApplicationResponse,
    SimpleMessage,
    StageProgress,
    SurveyAvailabilityRequest,
)
from app.schemas.audit import AuditLogResponse
from app.schemas.auth import (
    ChangePasswordRequest,
    LocalePreferenceRequest,
    LoginRequest,
    RequestOtpRequest,
    RequestOtpResponse,
    SignupAadhaarRequest,
    SignupAadhaarResponse,
    SignupCompleteRequest,
    SignupStartRequest,
    SignupStartResponse,
    SignupVerifyAadhaarRequest,
    SignupVerifyAadhaarResponse,
    SignupVerifyMobileRequest,
    SignupVerifyMobileResponse,
    Token,
    TokenPayload,
    UserCreate,
    UserResponse,
    VerifyOtpRequest,
)
from app.schemas.user import (
    OfficerCreateRequest,
    OfficerCreateResponse,
    UserAdminResponse,
    UserRoleUpdateRequest,
    UserStatusUpdateRequest,
)

from app.schemas.common import ChainVerification, PageMeta
from app.schemas.discrepancy import (
    DiscrepancyBase,
    DiscrepancyCreate,
    DiscrepancyResolveRequest,
    DiscrepancyResponse,
)
from app.schemas.document import DocumentBase, DocumentCreate, DocumentResponse
from app.schemas.encumbrance import (
    EncumbranceBase,
    EncumbranceCreate,
    EncumbranceResponse,
    EncumbranceUpdate,
)
from app.schemas.mutation import (
    MutationActionRequest,
    MutationBase,
    MutationCreate,
    MutationResponse,
    MutationStatsResponse,
)
from app.schemas.notification import (
    NotificationBase,
    NotificationCreate,
    NotificationResponse,
    NotificationUpdate,
)
from app.schemas.parcel import ParcelBase, ParcelCreate, ParcelGISResponse, ParcelResponse
from app.schemas.registration_record import (
    RegistrationRecordBase,
    RegistrationRecordCreate,
    RegistrationRecordResponse,
)
from app.schemas.survey import SurveyBase, SurveyCreate, SurveyResponse

__all__ = [
    "Token",
    "TokenPayload",
    "LoginRequest",
    "RequestOtpRequest",
    "RequestOtpResponse",
    "VerifyOtpRequest",
    "SignupStartRequest",
    "SignupStartResponse",
    "SignupVerifyMobileRequest",
    "SignupVerifyMobileResponse",
    "SignupAadhaarRequest",
    "SignupAadhaarResponse",
    "SignupVerifyAadhaarRequest",
    "SignupVerifyAadhaarResponse",
    "SignupCompleteRequest",
    "ChangePasswordRequest",
    "LocalePreferenceRequest",
    "UserCreate",
    "UserResponse",
    "OfficerCreateRequest",
    "OfficerCreateResponse",
    "UserAdminResponse",
    "UserRoleUpdateRequest",
    "UserStatusUpdateRequest",

    "ParcelBase",
    "ParcelCreate",
    "ParcelResponse",
    "ParcelGISResponse",
    "ApplicationCreate",
    "ApplicationResponse",
    "StageProgress",
    "SurveyAvailabilityRequest",
    "SimpleMessage",
    "MutationBase",
    "MutationCreate",
    "MutationActionRequest",
    "MutationResponse",
    "MutationStatsResponse",
    "DiscrepancyBase",
    "DiscrepancyCreate",
    "DiscrepancyResolveRequest",
    "DiscrepancyResponse",
    "SurveyBase",
    "SurveyCreate",
    "SurveyResponse",
    "DocumentBase",
    "DocumentCreate",
    "DocumentResponse",
    "AuditLogResponse",
    "ChainVerification",
    "PageMeta",
    "DistrictOverviewResponse",
    "TehsilSummary",
    "OfficerMetric",
    "NotificationBase",
    "NotificationCreate",
    "NotificationUpdate",
    "NotificationResponse",
    "RegistrationRecordBase",
    "RegistrationRecordCreate",
    "RegistrationRecordResponse",
    "EncumbranceBase",
    "EncumbranceCreate",
    "EncumbranceUpdate",
    "EncumbranceResponse",
]
